version: "3.7"
services:
  bot:
    build: .
    environment:
      - VK_TOKEN=$VK_TOKEN
      - TG_TOKEN=$TG_TOKEN
      - MIGRATE_DB=$MIGRATE_DB
    volumes:
      - bot-data:/app/data
volumes:
  bot-data:
